name       : haskell-time-compat
version    : 1.9.3
release    : 1
source     :
    - https://hackage.haskell.org/package/time-compat-1.9.3/time-compat-1.9.3.tar.gz : bb6a44e667945ddca8ded93e041ee91986a4a19f59e149a5dd21fdb1bfa3db88
license    : BSD-3-Clause
component  : programming.haskell
summary    : Compatibility package for time
description: |
    This packages tries to compat as much of 'time' features as possible.
builddeps  :
    - haskell-base-orphans-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-base-orphans-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
